/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lafo.view.PopUp.Kasir;

import javax.swing.JLabel;
import lafo.entity.barang;
import lafo.entity.diskon;
import lafo.proses.DataBase.DataBaseOperator;
import lafo.proses.DataBase.Koneksi;

/**
 *
 * @author user
 */
public class CariDiskon extends javax.swing.JFrame {

    /**
     * Creates new form CariDiskon
     */
    public CariDiskon() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    Koneksi konDbLafo = new Koneksi();
    DataBaseOperator dbop = new DataBaseOperator(konDbLafo);
    barang barangTerpilih = new barang();
    diskon disc = new diskon();
    inputBarang inBr;

    public inputBarang getInBr() {
        return inBr;
    }

//    public void setInBr(inputBarang inBr) {
//        this.inBr = inBr;
//    }

    
    

    public void tampilDiskon(){
        String sql = "SELECT `kode_diskon`, `nama`, `jumlah_diskon`, `tenggat_diskon` FROM `diskon` WHERE 1";
        String[] field = {"kode diskon","nama diskon","jumlah diskon","tenggat diskon" };
        
        dbop.tabel(sql, field, jTableDiskon);
    }
    
//    inputBarang InputBarang = new inputBarang();
    public void klikTabelBarang(){

           disc.setKode(jTableDiskon.getValueAt(jTableDiskon.getSelectedRow(), 0).toString());
           disc.setNama(jTableDiskon.getValueAt(jTableDiskon.getSelectedRow(), 1).toString());
           disc.setJumlahDiskon(Float.valueOf(jTableDiskon.getValueAt(jTableDiskon.getSelectedRow(), 2).toString()));
           disc.setTenggatWaktu(jTableDiskon.getValueAt(jTableDiskon.getSelectedRow(), 0).toString());
           
           System.out.println(disc.getKode());
           inputBarang.diss=disc;
           inputBarang.SetDatDis();
//           inputBarang.jLabelDiskon.setText("anjing");
//           Diskon = disc;
//           inBr.SetDiskon(disc.getKode());
//           inBr.setjLabelDiskon(disc.getKode());
//           inBr.setjLabelNamaDiskon(disc.getNama());
           this.setVisible(false);
        
    }
    
    public diskon getDiskon(){
        return disc;
    }
    
    public void action(){
        this.setVisible(true);
        this.tampilDiskon();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldCariDiskon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDiskon = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldCariDiskon.setText("jTextField1");

        jTableDiskon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDiskon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDiskonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDiskon);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldCariDiskon)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextFieldCariDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableDiskonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDiskonMouseClicked
        // TODO add your handling code here:
        klikTabelBarang();
    }//GEN-LAST:event_jTableDiskonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CariDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CariDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CariDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CariDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CariDiskon ini = new CariDiskon();
                ini.action();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDiskon;
    private javax.swing.JTextField jTextFieldCariDiskon;
    // End of variables declaration//GEN-END:variables
}
