/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lafo.view.PopUp.Kasir;

import lafo.entity.barang;
import lafo.entity.diskon;
import lafo.entity.menu;
import lafo.proses.DataBase.DataBaseOperator;
import lafo.proses.DataBase.Koneksi;
import lafo.view.MainJframe;

/**
 *
 * @author mahmu
 */
public class Kasir_enter extends javax.swing.JFrame {

    /**
     * Creates new form Kasir_enter
     */
    public Kasir_enter() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchfiield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(1267, 773));

        searchfiield.setPreferredSize(new java.awt.Dimension(1120, 73));
        searchfiield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchfiieldActionPerformed(evt);
            }
        });
        searchfiield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchfiieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchfiieldKeyTyped(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(searchfiield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(searchfiield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchfiieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchfiieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchfiieldActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        klikTabelBarang();
    }//GEN-LAST:event_jTable1MouseClicked

    private void searchfiieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchfiieldKeyTyped
        // TODO add your handling code here:
//        cariDataBarang();
    }//GEN-LAST:event_searchfiieldKeyTyped

    private void searchfiieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchfiieldKeyReleased
        // TODO add your handling code here:
        cariDataBarang();
    }//GEN-LAST:event_searchfiieldKeyReleased

    Koneksi koneksiDBLafo = new Koneksi();
    DataBaseOperator DBLafoOp = new DataBaseOperator(koneksiDBLafo);
    MainJframe JframeUtama;
    barang barangTerpilih = new barang();
    menu mntp = new menu();
    String mode;

    public void setJframeUtama(MainJframe JframeUtama) {
        this.JframeUtama = JframeUtama;
    }
    
    private void tampilData(){
        String sql = "SELECT * FROM `menu`";
        String[] header = {"kode Menu","nama Menu","Harga","Kategori"};
        DBLafoOp.tabel(sql, header, jTable1);
        
    }
    
    public void cariDataBarang(){
        String sql = "SELECT * FROM `menu`";
        String[] header = {"kode Barang","nama Barang","stok","satuan"};
        DBLafoOp.tabel(sql, header, jTable1);
//        System.out.println(sql);
    }
    
    inputBarang InputBarang = new inputBarang();
    public void klikTabelBarang(){
       
        mntp.setKode(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        mntp.setNama(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        mntp.setHarga(Float.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString()) );
        mntp.setKategori(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        
        InputBarang.setFrameUtama(JframeUtama);
        InputBarang.setMntp(mntp);
        
        InputBarang.startRun();
            
        this.setVisible(false);
        
    }
    
    public void TampilDiskon(){
        String sql = "SELECT `kode_diskon`, `nama`, `jumlah_diskon`, `tenggat_diskon` FROM `diskon` WHERE 1";
        String[] field = {"kode diskon","nama diskon","jumlah diskon","tenggat diskon" };
        
        DBLafoOp.tabel(sql, field, jTable1);
    }
    
    public void Action(){
        this.setVisible(true);
        this.tampilData();
            
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir_enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir_enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir_enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir_enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Kasir_enter().setVisible(true);

                Kasir_enter ini = new Kasir_enter();
                ini.setVisible(true);
                ini.tampilData();
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField searchfiield;
    // End of variables declaration//GEN-END:variables
}
