/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lafo.PopUpMenu;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lafo.entity.menu;
import lafo.proses.DataBase.DataBaseOperator;
import lafo.proses.DataBase.Koneksi;
import lafo.view.MainJframe;
import lafo.view.PopUp.ManajemenBarang.tambahStok.PopUpCariKodeBarang;


/**
 *
 * @author Hp
 */
public class PopUpTambahMenu extends javax.swing.JFrame {
Koneksi konDbLaf = new Koneksi();
DataBaseOperator DbOp = new DataBaseOperator(konDbLaf);
menu tempmenu = new menu();
String mode;
  int x=0;

    /**
     * Creates new form PopUpTambahMenu
     */
    public PopUpTambahMenu() {
        initComponents();
        
    }
        
     
     
   public String generatekodemenu(){
     int intindexkodemn;
     String IndexKode;
        String kode ;
        String indexRs = "00";
        
         String nama=Jtextfieldnamamenu.getText();
        String inisial = nama.substring(0, 2).toUpperCase();
             
        kode = "MN"+inisial;
        String sql ="SELECT menu.kode_Menu FROM menu\n" +
            "WHERE menu.kode_Menu LIKE '"+kode+"%'\n" +
            "ORDER BY menu.kode_Menu DESC\n" +
            "LIMIT 1;";
        ResultSet rs = DbOp.getResultSql(sql, true);
        try {while (rs.next()) {                
                
                indexRs = rs.getString(1).substring(4,6);
            }
        
            
                intindexkodemn= Integer.valueOf(indexRs)+1;
                
                if (intindexkodemn < 10) {
                    IndexKode = "0"+intindexkodemn;
                }else{
                    IndexKode = intindexkodemn+"";
                }
            
    
            
            
            kode = "MN"+inisial+IndexKode;
            
            System.out.println(kode);
        
        } catch (SQLException ex) {
            Logger.getLogger(MainJframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

//        jTextField_kodebarang.setText(inisial);
        return kode;
 }
        
 public void tambahMenu(){
     tempmenu.setKode(Jtextfieldkodemenu.getText());
        tempmenu.setNama(Jtextfieldnamamenu.getText());
       tempmenu.setKategori(jComboBoxKategori.getEditor().getItem().toString());
         tempmenu.setHarga(Float.valueOf(textFieldHarga.getText()) );
         
 String sql = "INSERT INTO `menu` "
                + "(`kode_Menu`, `Nama_Menu`, `Hargai`, `Kategori`) "
                + "VALUES "
                + "('"+tempmenu.getKode()+"', '"+tempmenu.getNama()+"', '"+tempmenu.getHarga()+"','"+tempmenu.getKategori()+"')";
 
     System.out.println("sql");
// DbOp.DatabaseExecutor(sql, true);
        String massageSucc = "Berhasil Menambahkan "+tempmenu.getNama();
        JOptionPane.showMessageDialog(this, massageSucc);
 }
        
 public void Tampiltabel(){
     
     
     
     
 }
        public void TambahResep (){ 
            
            String kode = labelKodemenu.getText();
            String nama = labelnamabarang.getText();
            String qty = textFieldSatuan.getText();
            String satuan = labelsatuan.getText();
            
            String[] data = {kode,nama,qty,satuan};
            
            DefaultTableModel model = (DefaultTableModel)jTableresep.getModel();
            
            model.addRow(data);
            
}
        public void  Hapusresep(){
            DefaultTableModel model = (DefaultTableModel)jTableresep.getModel();
            
            model.removeRow(jTableresep.getSelectedRow());
        }
                public void clear (){
                    Jtextfieldkodemenu.setText("");
                    Jtextfieldnamamenu.setText("");
                    textFieldHarga.setText("");
                }

   
            
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBoxKategori = new javax.swing.JComboBox<>();
        label4 = new java.awt.Label();
        label1 = new java.awt.Label();
        Jtextfieldkodemenu = new java.awt.TextField();
        Jtextfieldnamamenu = new java.awt.TextField();
        textFieldHarga = new java.awt.TextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        labelnamabarang = new java.awt.Label();
        labelKodemenu = new java.awt.Label();
        textFieldSatuan = new java.awt.TextField();
        labelsatuan = new java.awt.Label();
        jButtonhapus = new javax.swing.JButton();
        jButtontambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableresep = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(226, 225, 225));
        jPanel1.setPreferredSize(new java.awt.Dimension(332, 494));

        jComboBoxKategori.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman" }));
        jComboBoxKategori.setMinimumSize(new java.awt.Dimension(248, 25));
        jComboBoxKategori.setPreferredSize(new java.awt.Dimension(248, 25));
        jComboBoxKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxKategoriActionPerformed(evt);
            }
        });

        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setText("Harga\n");

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("Kode Menu");

        Jtextfieldkodemenu.setPreferredSize(new java.awt.Dimension(248, 25));
        Jtextfieldkodemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextfieldkodemenuActionPerformed(evt);
            }
        });
        Jtextfieldkodemenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JtextfieldkodemenuKeyReleased(evt);
            }
        });

        Jtextfieldnamamenu.setPreferredSize(new java.awt.Dimension(248, 25));

        textFieldHarga.setPreferredSize(new java.awt.Dimension(377, 51));
        textFieldHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldHargaActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setText("Nama Menu");

        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setText("Kategori");

        labelnamabarang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelnamabarang.setText("Nama Barang\n");

        labelKodemenu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelKodemenu.setText("BRSU01");
        labelKodemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelKodemenuMouseClicked(evt);
            }
        });

        textFieldSatuan.setPreferredSize(new java.awt.Dimension(57, 21));

        labelsatuan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelsatuan.setText("/ Satuan\n");

        jButtonhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icon/Group 25 (2).png"))); // NOI18N
        jButtonhapus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonhapusActionPerformed(evt);
            }
        });

        jButtontambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icon/Group 24.png"))); // NOI18N
        jButtontambah.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtontambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontambahActionPerformed(evt);
            }
        });

        jTableresep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableresep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Qty", "Satuan"
            }
        ));
        jTableresep.setPreferredSize(new java.awt.Dimension(247, 137));
        jTableresep.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTableresepComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(jTableresep);

        jButton4.setBackground(new java.awt.Color(241, 102, 52));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(241, 102, 52));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Simpan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setText("Generate Kode");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelKodemenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textFieldSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jButtontambah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Jtextfieldnamamenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jtextfieldkodemenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                        .addComponent(jComboBoxKategori, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jtextfieldkodemenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(Jtextfieldnamamenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jComboBoxKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(textFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelKodemenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtontambah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(labelsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxKategoriActionPerformed

    private void jButtonhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonhapusActionPerformed
        // TODO add your handling code here:
       Hapusresep();
    }//GEN-LAST:event_jButtonhapusActionPerformed

    private void jButtontambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontambahActionPerformed
TambahResep();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtontambahActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
clear();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void JtextfieldkodemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextfieldkodemenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextfieldkodemenuActionPerformed

    private void labelKodemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKodemenuMouseClicked
        // TODO add your handling code here:
        PopUpCariKodeBarang carikode = new PopUpCariKodeBarang();
        carikode.setVisible(true);
    }//GEN-LAST:event_labelKodemenuMouseClicked

    private void jTableresepComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTableresepComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableresepComponentAdded

    private void JtextfieldkodemenuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtextfieldkodemenuKeyReleased
 if ((Jtextfieldnamamenu.getText().length() == 2)) {
            
        Jtextfieldkodemenu.setText(generatekodemenu());        // TODO add your handling code here:
    }//GEN-LAST:event_JtextfieldkodemenuKeyReleased
    }
    private void textFieldHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldHargaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String kode = generatekodemenu();
        Jtextfieldkodemenu.setText(kode);
    }//GEN-LAST:event_jButton1ActionPerformed
 
    /**
     * @param args the command line arguments
     */
 
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUpTambahMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUpTambahMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUpTambahMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUpTambahMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUpTambahMenu().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Jtextfieldkodemenu;
    private java.awt.TextField Jtextfieldnamamenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonhapus;
    private javax.swing.JButton jButtontambah;
    private javax.swing.JComboBox<String> jComboBoxKategori;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableresep;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label labelKodemenu;
    private java.awt.Label labelnamabarang;
    private java.awt.Label labelsatuan;
    private java.awt.TextField textFieldHarga;
    private java.awt.TextField textFieldSatuan;
    // End of variables declaration//GEN-END:variables

}
