/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lafo.view.PopUp.Barang;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.ServiceUIFactory;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import lafo.entity.barang;
import lafo.proses.DataBase.DataBaseOperator;
import lafo.proses.DataBase.Koneksi;
import lafo.view.MainJframe;

/**
 *
 * @author Hp
 */
public class PopUpTambahBarang extends javax.swing.JFrame {

    /**
     * Creates new form PopUpTambahBarang
     */
    public PopUpTambahBarang() {
        initComponents();
    }

    Koneksi jaringan = new Koneksi();
    DataBaseOperator operatorDBLafo = new DataBaseOperator(jaringan);
    barang tempBarang = new barang();
    
    MainJframe JframeUtama;

    public PopUpTambahBarang(MainJframe JframeUtama) {
        this.JframeUtama = JframeUtama;
    }
    
    
    public void setComboBox(){
        String sql = "SELECT barang.satuan FROM `barang` GROUP BY satuan;";
        ResultSet rs = operatorDBLafo.getResultSql(sql, true);
        
        try {
            while (rs.next()) {
                jComboBox_satuan.addItem(rs.getString(1));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(PopUpTambahBarang.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
    }

   //membuat kode barang
    public String generateKodeBarang(){
        //deklarasi variabel
        int intIndexKode = 1;
        String IndexKode;
        String kode ;
        
        //buat inisial
        String nama=jTextField_namabarang.getText();
        String inisial = nama.substring(0, 2).toUpperCase();
        
        //jika index kode kurang dari 10 akan ditambahi 0 diawal
        if (intIndexKode < 10) {
            IndexKode = "0"+intIndexKode;
        }else{
            IndexKode = intIndexKode+"";
        }
        
        //membuat kodesuplier
        kode = "BR"+inisial+IndexKode;
        
        String sql = "SELECT kode_barang FROM `barang` WHERE kode_barang = '"+kode+"';";
        ResultSet rs = operatorDBLafo.getResultSql(sql, true);
        
        try {
            while (rs.next()) {                
                intIndexKode++;
            }
            
            if (intIndexKode < 10) {
                IndexKode = "0"+intIndexKode;
            }else{
                IndexKode = intIndexKode+"";
            }
            
            kode = "BR"+inisial+IndexKode;
            
        } catch (SQLException ex) {
            Logger.getLogger(MainJframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

//        jTextField_kodebarang.setText(inisial);
        return kode;
    }
    
    public void tambahBarang(){
        tempBarang.setKode(jTextField_kodebarang.getText());
        tempBarang.setNama(jTextField_namabarang.getText());
        tempBarang.setSatuan(jComboBox_satuan.getEditor().getItem().toString());
        
        String sql = "INSERT INTO `barang` "
                + "(`kode_Barang`, `Nama_barang`, `satuan`) "
                + "VALUES "
                + "('"+tempBarang.getKode()+"', '"+tempBarang.getNama()+"', '"+tempBarang.getSatuan()+"')";
        
        operatorDBLafo.DatabaseExecutor(sql, true);
        String massageSucc = "Berhasil Menambahkan "+tempBarang.getNama();
        JOptionPane.showMessageDialog(this, massageSucc);
    }
    
    public void clear(){
        jTextField_kodebarang.setText("");
        jTextField_namabarang.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_kodebarang = new javax.swing.JLabel();
        jTextField_kodebarang = new javax.swing.JTextField();
        jLabel_namabarang = new javax.swing.JLabel();
        jTextField_namabarang = new javax.swing.JTextField();
        jLabel_kategoribarang = new javax.swing.JLabel();
        jComboBox_satuan = new javax.swing.JComboBox<>();
        jButtonTambahSatuan = new javax.swing.JButton();
        jButton_selesai1 = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        jButton_Clear1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_kodebarang.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel_kodebarang.setText("Kode Barang");

        jTextField_kodebarang.setBackground(new java.awt.Color(146, 147, 147));
        jTextField_kodebarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_kodebarangActionPerformed(evt);
            }
        });

        jLabel_namabarang.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel_namabarang.setText("Nama Barang");

        jTextField_namabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_namabarangActionPerformed(evt);
            }
        });
        jTextField_namabarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_namabarangKeyTyped(evt);
            }
        });

        jLabel_kategoribarang.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel_kategoribarang.setText("satuan");

        jComboBox_satuan.setEditable(true);
        jComboBox_satuan.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        jComboBox_satuan.setToolTipText("");
        jComboBox_satuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_satuanActionPerformed(evt);
            }
        });

        jButtonTambahSatuan.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        jButtonTambahSatuan.setText("tambah");
        jButtonTambahSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahSatuanActionPerformed(evt);
            }
        });

        jButton_selesai1.setBackground(new java.awt.Color(241, 102, 52));
        jButton_selesai1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_selesai1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_selesai1.setText("SIMPAN");
        jButton_selesai1.setPreferredSize(new java.awt.Dimension(476, 46));
        jButton_selesai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_selesai1ActionPerformed(evt);
            }
        });

        jButton_Clear.setBackground(new java.awt.Color(241, 102, 52));
        jButton_Clear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Clear.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Clear.setText("CLEAR");
        jButton_Clear.setPreferredSize(new java.awt.Dimension(476, 46));
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });

        jButton_Clear1.setBackground(new java.awt.Color(159, 162, 171));
        jButton_Clear1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Clear1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Clear1.setText("CANCEL");
        jButton_Clear1.setPreferredSize(new java.awt.Dimension(476, 46));
        jButton_Clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Clear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel_kategoribarang)
                        .addComponent(jLabel_namabarang)
                        .addComponent(jTextField_namabarang)
                        .addComponent(jLabel_kodebarang)
                        .addComponent(jTextField_kodebarang)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jComboBox_satuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonTambahSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton_selesai1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel_kodebarang, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_kodebarang, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_namabarang, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_namabarang, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_kategoribarang, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_satuan, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jButtonTambahSatuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(jButton_selesai1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(jButton_Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(jButton_Clear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_kodebarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_kodebarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_kodebarangActionPerformed

    private void jTextField_namabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_namabarangActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_namabarangActionPerformed

    private void jButton_selesai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_selesai1ActionPerformed
        // TODO add your handling code here:
        tambahBarang();
        this.setVisible(false);
        JframeUtama.DisplayTabelBarang();
    }//GEN-LAST:event_jButton_selesai1ActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jButton_Clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Clear1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton_Clear1ActionPerformed

    private void jComboBox_satuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_satuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_satuanActionPerformed

    private void jTextField_namabarangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_namabarangKeyTyped
        // TODO add your handling code here:
        if (jTextField_namabarang.getText().length() == 2) {
            
            System.out.println(generateKodeBarang());
            jTextField_kodebarang.setText(generateKodeBarang());
        }
    }//GEN-LAST:event_jTextField_namabarangKeyTyped

    private void jButtonTambahSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahSatuanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonTambahSatuanActionPerformed

    
    public void startRun(){
//        this.main();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUpTambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUpTambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUpTambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUpTambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PopUpTambahBarang tambahBarang = new PopUpTambahBarang();
                
                tambahBarang.setVisible(true);
                tambahBarang.setComboBox();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTambahSatuan;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Clear1;
    private javax.swing.JButton jButton_selesai1;
    private javax.swing.JComboBox<String> jComboBox_satuan;
    private javax.swing.JLabel jLabel_kategoribarang;
    private javax.swing.JLabel jLabel_kodebarang;
    private javax.swing.JLabel jLabel_namabarang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_kodebarang;
    private javax.swing.JTextField jTextField_namabarang;
    // End of variables declaration//GEN-END:variables
}
